### ISSUE TITLE
kan e.v.t. korter

### ISSUE THREAD

**Issue by jody29** [juliandecloe/My-Progressive-Web-App#2]
https://github.com/juliandecloe/My-Progressive-Web-App/blob/f7f04892ed5a6751809cd7af10cb1221981eeca1/app.js#L24-L26

ipv `.then(response => {
  return response.json()
})
`
kun je `.then(response => response.json())` doen.
Dan zijn de curly brackets en return niet meer nodig

**Comment by juliandecloe** [comment]
Code is ingekort. Bedankt voor het advies!
